debug: false
server:
  hostname: localhost
  port: 8080
  ssl: false
  gql_introspection: true
  origins:
    - http://localhost:8080
    - http://localhost:3000
database:
  username: cble
  password: cble
  host: 127.0.0.1
  ssl: false
providers:
  cache: "/tmp/cble-providers"
auth:
  jwt_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  session_timeout: 1440 # 24 hours * 60 mins
initialization:
  default_admin:
    first_name: CBLE
    last_name: Admin
    username: cble
    password: cble
  admin_group: CBLE Administrators
  permissions:
    # Users
    - key: com.cble.users.list
      component: Users
      description: List users
    - key: com.cble.users.create
      component: Users
      description: Create users
    - key: com.cble.users.read
      component: Users
      description: Retrieve users
    - key: com.cble.users.update
      component: Users
      description: Update users
    - key: com.cble.users.delete
      component: Users
      description: Delete users
    # Groups
    - key: com.cble.groups.list
      component: Groups
      description: List groups
    - key: com.cble.groups.create
      component: Groups
      description: Create groups
    - key: com.cble.groups.read
      component: Groups
      description: Retrieve groups
    - key: com.cble.groups.update
      component: Groups
      description: Update groups
    - key: com.cble.groups.delete
      component: Groups
      description: Delete groups
    # Providers
    - key: com.cble.providers.list
      component: Providers
      description: List providers
    - key: com.cble.providers.create
      component: Providers
      description: Create providers
    - key: com.cble.providers.read
      component: Providers
      description: Retrieve providers
    - key: com.cble.providers.update
      component: Providers
      description: Update providers
    - key: com.cble.providers.delete
      component: Providers
      description: Delete providers
    - key: com.cble.providers.load
      component: Providers
      description: Load providers
    - key: com.cble.providers.unload
      component: Providers
      description: Unload providers
    - key: com.cble.providers.configure
      component: Providers
      description: Apply configuration to providers
    # Provider Commands
    - key: com.cble.providercommands.list
      component: Provider Commands
      description: List provider commands
    - key: com.cble.providercommands.create
      component: Provider Commands
      description: Create provider commands
    - key: com.cble.providercommands.read
      component: Provider Commands
      description: Retrieve provider commands
    - key: com.cble.providercommands.update
      component: Provider Commands
      description: Update provider commands
    - key: com.cble.providercommands.delete
      component: Provider Commands
      description: Delete provider commands
    # Blueprints
    - key: com.cble.blueprints.list
      component: Blueprints
      description: List blueprints
    - key: com.cble.blueprints.create
      component: Blueprints
      description: Create blueprints
    - key: com.cble.blueprints.read
      component: Blueprints
      description: Retrieve blueprints
    - key: com.cble.blueprints.update
      component: Blueprints
      description: Update blueprints
    - key: com.cble.blueprints.delete
      component: Blueprints
      description: Delete blueprints
    - key: com.cble.blueprints.deploy
      component: Blueprints
      description: Deploy blueprints
    # Deployments
    - key: com.cble.deployments.list
      component: Deployments
      description: List deployments
    - key: com.cble.deployments.get
      component: Deployments
      description: Retrieve deployments
    - key: com.cble.deployments.destroy
      component: Deployments
      description: Destroy deployments
    - key: com.cble.deployments.redeploy
      component: Deployments
      description: Redeploy deployments
    - key: com.cble.deployments.console
      component: Deployments
      description: Get deployment vm console
